
SELECT ITEM_INFO.ITEM_CODE, ITEM_NAME FROM ITEM_INFO
WHERE ITEM_CODE IN (
	SELECT ITEM_CODE FROM ITEM_QUANTITIES
	WHERE ORDER_ID = (
		SELECT ORDER_ID  FROM [ORDER ID]
		WHERE UNAME = (
			SELECT UNAME FROM [PERSON_INFO]
			WHERE FNAME = 'Kaivalya' AND LNAME = 'Pullakandam'
)))	