SELECT ITEM_INFO.ITEM_NAME, ITEM_QUANTITIES.QUANTITY 
FROM ITEM_QUANTITIES

LEFT JOIN  ITEM_INFO
ON ITEM_INFO.ITEM_CODE = ITEM_QUANTITIES.ITEM_CODE 

WHERE ITEM_QUANTITIES.ORDER_ID = (
		SELECT ORDER_ID FROM [ORDER ID]
		WHERE UNAME = (
			SELECT UNAME FROM PERSON_INFO
			WHERE FNAME = 'Kaivalya' AND LNAME = 'Pullakandam'
))
